<?php
########################################################################
#
# Theme : theme_bootstrap4_kern
# Created : 2017-09-13 - 14:23:32
#
# Auto generated by FTM
#
# www.fluid-template-manager.de
#
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title'            => 'Theme-Bootstrap4-Child',
	'description'      => 'Theme for your Website',
	'category'         => 'templates',
	'shy'              => 0,
	'version'          => '0.0.1',
	'dependencies'     => '',
	'conflicts'        => '',
	'priority'         => 'bottom',
	'loadOrder'        => '',
	'module'           => '',
	'state'            => 'stable',
	'uploadfolder'     => 0,
	'createDirs'       => '',
	'modify_tables'    => '',
	'clearcacheonload' => 0,
	'lockType'         => '',
	'author'           => '',
	'author_email'     => '',
	'author_company'   => '',
	'CGLcompliance'      => '',
	'CGLcompliance_note' => '',
	'constraints' => array(
		'depends' => array(
			'themes' => '8.7.0-8.7.99',
			'theme_bootstrap4' => '0.7.0',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
	'_md5_values_when_last_written' => ''
);